Features
RytisMiciunas/Selenium pull request #1
Opened 2024-02-26 10:27 UTC by RytisMiciunas

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +import os.path
Padaryk biblioteku grupavima, kad graziau ir patogiau butu

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +
Viska sukelk i funkcijas
vienas veiksmas - viena funkcija

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +pathToDriver = r"C:\Users\rmiciun\chromedriver-win64-122\chromedriver.exe"
chromedriver.exe gali laikyti tame paciame folderyje. tai path trumpesnins bus

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.get("https://www.orioninc.com")
visas constant sukelk i atskira faila, kuriame bus saugomos constant variables

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.implicitly_wait(3)
Kam reikia implicity_wait?

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.find_element(By.ID,'hs-eu-confirmation-button').click()
visus xpath irgi iskelk is pagrindinio failo

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.find_element(By.XPATH, "//*[@id='post-108']/div/div[1]/div[2]/div[1]/div/div[2]/div[2]/b").click()
visus xpath irgi iskelk is pagrindinio failo

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +wait.until(lambda x: x.find_element(By.ID, "search-filter"))
Kam reikia lambda? kaip tai veikia? Gal net nereikalinga visa eilute????

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +inputInformation = theChosenLine.split()
pasidomek ar yra biblioteku name, email, number,... generation

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.find_element(By.XPATH, "//*[@id='post-108']/div/div[1]/div[2]/div[1]/div/div[2]/div[2]/b").click()
Pasidomek elementu paieskos hierarchija :) 
Issiaiskink koks yra skirtumas tarp relative ir absolute xpath.
Truksta vientisumo (naudoji dvi skirtingass xpath formas) - apsispresk.

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +try:
Good, kad naudoji try, except - mldc.

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +    wait.until(EC.frame_to_be_available_and_switch_to_it((By.ID, 'grnhse_iframe')))
Good, kad naudoji EC

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +keyboard.release(Key.enter)
Pasidomek kaip uploadint faila naudojant TIK SELENIUM :) (Keyboard - nera reikalingas, galima paprasciau, bet hey hey smagu kad suradai alternatyva)

2024-02-26 10:47 UTC, Tautvydas-coder commented on script_form.py
> +driver.find_element(By.ID, 'submit_buttons').click()
Good practice - uzdaryti tai ka paleidai (webdriver, file read,...)

2024-02-26 10:55 UTC, RytisMiciunas commented on script_form.py
> +keyboard.release(Key.enter)
Del sito zn kad galima su send.keys() bet man kazkodel neinputindavo tai padariau per cia :v

2024-02-26 15:51 UTC, RytisMiciunas commented on script_form.py
> +wait.until(lambda x: x.find_element(By.ID, "search-filter"))
Lambda eilute laukia kol atsiras elementas su ID "search-filter". X paimamas WebDriver instance ir su find_element ieskomas elementas. Galima pakeist i wait.until(EC.visibility_of_element_located((By.ID, 'search-filter')))

2024-02-26 15:58 UTC, RytisMiciunas commented on script_form.py
> +driver.implicitly_wait(3)
Kad uzsikrautu puslapis. Panaudojau vietoj sleep(3), nes implicity_wait jei randa sekanti elementa nelaukia viso laiko

2024-02-27 13:57 UTC, Tautvydas-coder requested changes

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/__pycache__/Functions.cpython-312.pyc
Pycache geriau nekelk, nereikalingi jie

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/script_form.py
Pycache geriau nekelk, nereikalingi jie

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/Functions.py
> +    driver.get("https://www.orioninc.com")
URL i Variables iskelk faila

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/script_form.py
> +
https://stackoverflow.com/questions/4042905/what-is-main-py - paskaityk ir perdaryk atitinkamai :)

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/variables.py
> +selectingVilnius = "//li[contains(text(), 'Vilnius')]"
https://www.w3schools.com/python/python_variables_names.asp
Bet gerai ir kaip tu rasai. Nenustebk kad ateityje rays kitaip, nes del patogumo buna kad nutaria is anksto kokia stilistika bus naudojama, nes tai priklauso nuo projekto

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/variables.py
> -uploadCv = '//*[@id="resume_fieldset"]/div/div[3]/button[1]'
Consistency with naming - vienur variables pabrezi koks yra elementas (pvz. technologyAndEngineeringCheckBox), o kitur nepabrezi pvz acceptCookie.
Missleading pavadinimai - careersButton

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/variables.py
> -inputPhone = 'phone'
Jei tai yra string values, gali perkelti i kita atskira faila (kaip variables, konstantas). 
Jeigu tai yra xpath, tai pakeisk pavadinima (pvz. inputNameElementId)
del to gereja skaitomumas

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/script_form.py
> +import Functions as fun
fun nėra aiškiai suprantamas pavadinimas. 
Reikia aiškesnio, nes kai bus tūkstančiai eilučių kodo, nebus aišku ka tai reiskia, kodėl tai yra ir kas tai.

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/Functions.py
> +    driver = checkAndOpenDriver(path)
Geriau funkcijas deklaruok pries ju iskvietima.

2024-02-27 13:57 UTC, Tautvydas-coder commented on testing_script/Functions.py
> +def checkAndOpenDriver(path):
pagalbines funkcijas gali i kita faila isikelti

2024-02-28 08:56 UTC, Tautvydas-coder approved these changes

2024-02-28 08:57 UTC, merged